name: Run Stock Monitor

on:
  schedule:
    - cron: '0 */4 * * *' # Roda a cada 4 horas para garantir que se o script principal cair, uma máquina reserva assume
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest
    # Configura o tempo máximo total que este job pode rodar antes do GitHub reiniciar (6 horas é o limite da plataforma)
    timeout-minutes: 350 

    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v3

      - name: Setup Node.js Environment
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y wget curl unzip
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Install Dependencies
        run: npm install

      - name: Execute Monitor Script
        run: node stock_monitor.js
