name: Run Stock Monitor

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v3

      - name: Setup Node.js Environment
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # PASSO NOVO: Garante que o navegador necessário para burlar o Cloudflare esteja instalado na nuvem
      - name: Install Chromium Browser on Linux
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser

       Richmond- Install Dependencies
        run: npm install

      - name: Execute Monitor Script
        run: node stock_monitor.js
